console.log("settings imported");
const BorderColor = "darkgreen";
const OutlineColor = "black";
const BackgroundColor = "green";
const CellHeight = 30;
const CellWidth = 30;
const BorderSize = 5;
const OutlineSize = 10;
const Columns = 9;
const Rows = 9;
const TicksPerSec = 4;
const dev = false;